### ISSUE TITLE
Windows Executeable Fails to Launch

### ISSUE THREAD

**Issue by Anewidea** [DeepLcom/deepl-dotnet#27]
My deepL windows application all of a sudden stopped working after it updated. Now the Translate Text screen is blank and in the log it says it keeps trying to restart (infinite loop).
![image](https://user-images.githubusercontent.com/2049722/222919903-f4a9478a-60f2-4328-bec0-f5ed523a8263.png)

I've verified that I'm not having firewall issues since in the log it creates this screen from a URL
[0303/094925.825:INFO:render_frame_host_impl.cc(11654)] RenderFrameHostImpl::MaybeGenerateCrashReport url = https://www.deepl.com/en/windows/translator?windows_app_version=4.5.0.8268&theme=1, status = 0, exit_code = 0
I do not think this is a connection issue since I can open the page just fine in my browser.
![image](https://user-images.githubusercontent.com/2049722/222920008-6a1e2762-dc35-4d10-bdfc-86da8cac84c0.png)

Application: DeepL.exe
CoreCLR Version: 6.0.1423.7309
.NET Version: 6.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: [DIE] This scope "Container" is already disposed, so it can't create a "global::DeepL.Utilities.Scheduling.IHaveMainScheduler" instance anymore.
Object name: 'Container'.
   at DeepL.DI.Container.CreateIHaveMainScheduler_27_0()
   at DeepL.DI.Container.<GetContainerInstanceApp_8_0>b__14_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at DeepL.Views.AppContext.Initialize()
   at DeepL.Views.App.<>c__DisplayClass21_0.<.ctor>g__OnStartupLocal|4(Object sender, EventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at DeepL.Views.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DeepL.Program.RunAsFirstInstance()
   at DeepL.Program.Run()
   at DeepL.Program.Main(String[] args)

**Comment by dieter-enns-deepl** [comment]
Hello,

could you please send us the logs? They would help us getting a better understanding of the issue.
Please use the in-app feedback function (from the hamburger menu). There you should be able to append the logs as well as a message. I would ask you to put the UUID "4B3705B2-7420-46B4-822F-F979DFA635D6" to the message, so we can match it to this issue quickly. In general the feedback function is anonymous and the logs will be encrypted before being transfered.

**Comment by seekuehe** [comment]
Hello,

This issue is not related to the client library, so we will close this. Please reach out to support@deepl.com.
