### ISSUE TITLE
Translations from German to English generate errors

### ISSUE THREAD

**Issue by datan0stra** [DeepLcom/deepl-dotnet#6]
Hello,

we use version 1.0.4.

If we try to translate "Dog" from english to german like this ...

**var translator = new Translator(Settings.DeeplTranslatorTextKey);
TextResult textResult = await translator.TranslateTextAsync("Dog", LanguageCode.EnglishAmerican, LanguageCode.German);**

... we get the following error:

**Bad request, message: Value for 'source_lang' not supported.**

   at DeepL.Internal.DeepLClient.<CheckStatusCodeAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DeepL.Translator.<TranslateTextAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at DeepL.Translator.<TranslateTextAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

If we try to translate "Hund" from german to english, everything works fine.

**Comment by daniel-jones-deepl** [comment]
Hi @datan0stra,
`LanguageCode.EnglishAmerican` cannot be used as a source language, use `LanguageCode.English` instead. Otherwise your code looks correct.

**Comment by datan0stra** [comment]
Thank you for your quick reply!

Now I understood the trick: The source language must be LanguageCode.English and must not be LanguageCode.EnglishAmerican or LanguageCode.EnglishBritish, while the target language must be LanguageCode.EnglishAmerican or LanguageCode.EnglishBritish but must not be LanguageCode.English, otherwise it will generate the following error message: targetLanguageCode="en" is deprecated, please use "en-GB" or "en-US" instead.

Thanks for the help!

**Comment by gregzhadko** [comment]
@daniel-jones-deepl it looks weird. When I use the enum in the code, I expect the same values to be used as target and source languages. How can I figure out that without reading this issue?

**Comment by daniel-jones-deepl** [comment]
Hi @gregzhadko, we've [documented the enum values](https://github.com/DeepLcom/deepl-dotnet/blob/main/DeepL/LanguageCode.cs#L27) stating whether they can be used as a source language, target language, or both. Of course, documentation on enum values isn't always easy to find, e.g. it depends on the IDE one uses.

We could add a note about these language codes to the readme. Do you think that would have prevented you from having to read this issue?

**Comment by gregzhadko** [comment]
Hi @daniel-jones-deepl, I have tested it on my end, and unfortunately, I couldn't find any documentation related to `Language` enum. I have thoroughly examined the source code by decompiling and even checked the IDE (Rider), but to no avail. Do you think it's possible that the documentation got lost during the Nuget building process?
